Small RSS: addChannel Class Reference
addChannel Class Reference
QDialog offering the user an option to add new RSS channel.
#include <addchannel.h>
Public Member Functions
addChannel (QWidget *parent=nullptr)
generic constructor. Inits the view.
~addChannel ()
generic destructor
int lastStatus ()
Method to check for the last HTTP status code.
QVector< ChannelParser::itemInfo > getChannelItems () const
Getter method for items from the freshly added channel.
ChannelParser::channelInfo getChannelInfo () const
Getter method for details of freshly added channel.
Private Slots
void finished (QNetworkReply *reply)
Method processing network replies when adding the channel.
void add ()
Method sending GET request asking for RSS channel info and data.
void verifyBtns ()
Helper method making sure that appropriate buttons are disabled until input has data in more or less correct format.
Private Attributes
Ui::addChannel * ui
user interface pointer
QNetworkAccessManager * manager
NetworkAccessManager instance used to get the data of the channel.
int status
Holds last received HTTP status code.
ChannelParser parser
Instance of the parser to extract data from XML.
QVector< ChannelParser::itemInfo > items
Vector holding last retrieved items from the channel.
ChannelParser::channelInfo chinfo
Structure with channel info data.
Detailed Description
QDialog offering the user an option to add new RSS channel.
Definition at line 17 of file addchannel.h.
Constructor & Destructor Documentation
addChannel()
addChannel::addChannel (QWidget * parent = nullptr) explicit
generic constructor. Inits the view.
Parameters
parent Parent widget, defaults to nullptr
Definition at line 4 of file addchannel.cpp.
References add(), finished(), ChannelParser::init(), manager, parser, status, ui, and verifyBtns().
~addChannel()
addChannel::~addChannel ()
generic destructor
Definition at line 23 of file addchannel.cpp.
References ui.
Member Function Documentation
add
void addChannel::add () private slot
Method sending GET request asking for RSS channel info and data.
Definition at line 32 of file addchannel.cpp.
References manager, and ui.
Referenced by addChannel().
finished
void addChannel::finished (QNetworkReply * reply) private slot
Method processing network replies when adding the channel.
Parameters
reply Pointer to QNetworkReply object holding the reply data
Definition at line 36 of file addchannel.cpp.
References chinfo, ChannelParser::getChannelInfo(), ChannelParser::getItemsInfo(), items, ChannelParser::parseData(), parser, and status.
Referenced by addChannel().
getChannelInfo()
ChannelParser::channelInfo addChannel::getChannelInfo () const
Getter method for details of freshly added channel.
Returns
ChannelParser::channelInfo data set
See also
ChannelParser::channelInfo
Definition at line 60 of file addchannel.cpp.
References chinfo.
Referenced by MainWindow::addChannel().
getChannelItems()
QVector< ChannelParser::itemInfo > addChannel::getChannelItems () const
Getter method for items from the freshly added channel.
Returns
Vector with ChannelParser::itemInfo data or empty QVector
See also
ChannelParser::itemInfo
Definition at line 56 of file addchannel.cpp.
References items.
Referenced by MainWindow::addChannel().
lastStatus()
int addChannel::lastStatus ()
Method to check for the last HTTP status code.
Returns
Last HTTP status code
Definition at line 52 of file addchannel.cpp.
References status.
verifyBtns
void addChannel::verifyBtns () private slot
Helper method making sure that appropriate buttons are disabled until input has data in more or less correct format.
Definition at line 28 of file addchannel.cpp.
References ui.
Referenced by addChannel().
Member Data Documentation
chinfo
ChannelParser::channelInfo addChannel::chinfo private
Structure with channel info data.
See also
ChannelParser::channelInfo
Definition at line 49 of file addchannel.h.
Referenced by MainWindow::addChannel(), finished(), and getChannelInfo().
items
QVector<ChannelParser::itemInfo> addChannel::items private
Vector holding last retrieved items from the channel.
See also
ChannelParser::itemInfo
Definition at line 48 of file addchannel.h.
Referenced by finished(), and getChannelItems().
manager
QNetworkAccessManager* addChannel::manager private
NetworkAccessManager instance used to get the data of the channel.
Definition at line 45 of file addchannel.h.
Referenced by add(), and addChannel().
parser
ChannelParser addChannel::parser private
Instance of the parser to extract data from XML.
Definition at line 47 of file addchannel.h.
Referenced by addChannel(), and finished().
status
int addChannel::status private
Holds last received HTTP status code.
Definition at line 46 of file addchannel.h.
Referenced by addChannel(), finished(), and lastStatus().
ui
Ui::addChannel* addChannel::ui private
user interface pointer
Definition at line 44 of file addchannel.h.
Referenced by add(), addChannel(), verifyBtns(), and ~addChannel().
The documentation for this class was generated from the following files:
addchannel.h
addchannel.cpp