Small RSS: optiondlg Class Reference
optiondlg Class Reference
#include <optiondlg.h>
Public Slots
void reloadSettings ()
Signals
void newDBclicked ()
void moveDBClicked (QString target)
void clearCacheClicked ()
void moveCacheClicked (QString target)
void openDBClicked ()
void clearDBClicked ()
Public Member Functions
optiondlg (QWidget *parent=nullptr)
~optiondlg ()
Protected Member Functions
void changeEvent (QEvent *e)
Private Slots
void moveDB ()
void moveCache ()
void help ()
void ok ()
void selectFile ()
void selectFolder ()
Private Member Functions
void recalculateSizes ()
qint64 getDirSize (QString dir)
Private Attributes
Ui::optiondlg * ui
QSettings settings
QAction * findFile
QAction * findFolder
Detailed Description
Definition at line 31 of file optiondlg.h.
Constructor & Destructor Documentation
optiondlg()
optiondlg::optiondlg (QWidget * parent = nullptr) explicit
Definition at line 18 of file optiondlg.cpp.
References clearCacheClicked(), clearDBClicked(), findFile, findFolder, help(), moveCache(), moveDB(), newDBclicked(), ok(), openDBClicked(), recalculateSizes(), reloadSettings(), selectFile(), selectFolder(), and ui.
~optiondlg()
optiondlg::~optiondlg ()
Definition at line 44 of file optiondlg.cpp.
References ui.
Member Function Documentation
changeEvent()
void optiondlg::changeEvent (QEvent * e) protected
Definition at line 49 of file optiondlg.cpp.
References ui.
clearCacheClicked
void optiondlg::clearCacheClicked () signal
Referenced by optiondlg().
clearDBClicked
void optiondlg::clearDBClicked () signal
Referenced by optiondlg().
getDirSize()
qint64 optiondlg::getDirSize (QString dir) private
Definition at line 79 of file optiondlg.cpp.
Referenced by recalculateSizes().
help
void optiondlg::help () private slot
Definition at line 112 of file optiondlg.cpp.
Referenced by optiondlg().
moveCache
void optiondlg::moveCache () private slot
Definition at line 102 of file optiondlg.cpp.
References moveCacheClicked(), recalculateSizes(), reloadSettings(), and ui.
Referenced by optiondlg().
moveCacheClicked
void optiondlg::moveCacheClicked (QString target) signal
Referenced by moveCache().
moveDB
void optiondlg::moveDB () private slot
Definition at line 93 of file optiondlg.cpp.
References moveDBClicked(), reloadSettings(), and ui.
Referenced by optiondlg().
moveDBClicked
void optiondlg::moveDBClicked (QString target) signal
Referenced by moveDB().
newDBclicked
void optiondlg::newDBclicked () signal
Referenced by optiondlg().
ok
void optiondlg::ok () private slot
Definition at line 116 of file optiondlg.cpp.
References settings, and ui.
Referenced by optiondlg().
openDBClicked
void optiondlg::openDBClicked () signal
Referenced by optiondlg().
recalculateSizes()
void optiondlg::recalculateSizes () private
Definition at line 72 of file optiondlg.cpp.
References getDirSize(), settings, and ui.
Referenced by moveCache(), and optiondlg().
reloadSettings
void optiondlg::reloadSettings () slot
Definition at line 61 of file optiondlg.cpp.
References settings, and ui.
Referenced by moveCache(), moveDB(), and optiondlg().
selectFile
void optiondlg::selectFile () private slot
Definition at line 129 of file optiondlg.cpp.
References ui.
Referenced by optiondlg().
selectFolder
void optiondlg::selectFolder () private slot
Definition at line 137 of file optiondlg.cpp.
References ui.
Referenced by optiondlg().
Member Data Documentation
findFile
QAction* optiondlg::findFile private
Definition at line 45 of file optiondlg.h.
Referenced by optiondlg().
findFolder
QAction* optiondlg::findFolder private
Definition at line 46 of file optiondlg.h.
Referenced by optiondlg().
settings
QSettings optiondlg::settings private
Definition at line 44 of file optiondlg.h.
Referenced by ok(), recalculateSizes(), and reloadSettings().
ui
Ui::optiondlg* optiondlg::ui private
Definition at line 43 of file optiondlg.h.
Referenced by changeEvent(), moveCache(), moveDB(), ok(), optiondlg(), recalculateSizes(), reloadSettings(), selectFile(), selectFolder(), and ~optiondlg().
The documentation for this class was generated from the following files:
optiondlg.h
optiondlg.cpp