Small RSS: channelEditDialog Class Reference
channelEditDialog Class Reference
Simple editor of properties of RSS channel as a modal dialog.
#include <channeleditdialog.h>
Public Member Functions
channelEditDialog (QWidget *parent=nullptr)
Generic constructor. Inits the view.
~channelEditDialog ()
Generic destructor.
void setData (QSqlRecord record)
Setter method for the view items.
QSqlRecord getData () const
Getter method for the altered channel.
Private Slots
void fillData ()
Method fills the form with ori record data.
Private Attributes
Ui::channelEditDialog * ui
User interface pointer.
QSqlRecord ori
Holder var for source record.
Detailed Description
Simple editor of properties of RSS channel as a modal dialog.
Definition at line 14 of file channeleditdialog.h.
Constructor & Destructor Documentation
channelEditDialog()
channelEditDialog::channelEditDialog (QWidget * parent = nullptr) explicit
Generic constructor. Inits the view.
Parameters
parent Optional parent object pointer or nullptr
Definition at line 4 of file channeleditdialog.cpp.
References fillData(), and ui.
~channelEditDialog()
channelEditDialog::~channelEditDialog ()
Generic destructor.
Definition at line 23 of file channeleditdialog.cpp.
References ui.
Member Function Documentation
fillData
void channelEditDialog::fillData () private slot
Method fills the form with ori record data.
See also
setData()
ori
Definition at line 33 of file channeleditdialog.cpp.
References ori, and ui.
Referenced by channelEditDialog(), and setData().
getData()
QSqlRecord channelEditDialog::getData () const
Getter method for the altered channel.
Please note that it only holds valid data if dialog has been closed with "accept" button.
Returns
Complete record with all the parameters (not only altered ones).
Definition at line 57 of file channeleditdialog.cpp.
References ori, and ui.
Referenced by MainWindow::editChannel().
setData()
void channelEditDialog::setData (QSqlRecord record)
Setter method for the view items.
Parameters
record Database record with channel parameters
Definition at line 28 of file channeleditdialog.cpp.
References fillData(), and ori.
Referenced by MainWindow::editChannel().
Member Data Documentation
ori
QSqlRecord channelEditDialog::ori private
Holder var for source record.
Definition at line 38 of file channeleditdialog.h.
Referenced by fillData(), getData(), and setData().
ui
Ui::channelEditDialog* channelEditDialog::ui private
User interface pointer.
Definition at line 37 of file channeleditdialog.h.
Referenced by channelEditDialog(), fillData(), getData(), and ~channelEditDialog().
The documentation for this class was generated from the following files:
channeleditdialog.h
channeleditdialog.cpp