Small RSS: ChannelModel Class Reference
ChannelModel Class Reference
Simple QSqlTableModel descendant providing data for the list of channels.
#include <channelmodel.h>
Public Member Functions
ChannelModel (QObject *parent=nullptr, QSqlDatabase db=QSqlDatabase())
Generic constructor.
bool select () override
Simple override of generic select() with lazy model population off.
QVariant data (const QModelIndex &idx, int role=Qt::DisplayRole) const override
QSqlTableModel::data() override. Returns proper tooltips and icons.
Private Attributes
QSettings settings
Local access to program wide settings.
Detailed Description
Simple QSqlTableModel descendant providing data for the list of channels.
Definition at line 12 of file channelmodel.h.
Constructor & Destructor Documentation
ChannelModel()
ChannelModel::ChannelModel (QObject * parent = nullptr, QSqlDatabase db = QSqlDatabase())
Generic constructor.
Parameters
parent Optional parent object or nullptr
db Database instance
Definition at line 3 of file channelmodel.cpp.
Member Function Documentation
data()
QVariant ChannelModel::data (const QModelIndex & idx, int role = Qt::DisplayRole) const override
QSqlTableModel::data() override. Returns proper tooltips and icons.
Parameters
idx Index of the data from model
role Role of the data that index is pointing to
Returns
QVariant with data or empty QVariant() if data not available
Definition at line 16 of file channelmodel.cpp.
References data(), and settings.
Referenced by data().
select()
bool ChannelModel::select () override
Simple override of generic select() with lazy model population off.
Returns
true if model is successfuly populated
Definition at line 5 of file channelmodel.cpp.
Referenced by MainWindow::addChannel(), and MainWindow::initChannels().
Member Data Documentation
settings
QSettings ChannelModel::settings private
Local access to program wide settings.
Definition at line 32 of file channelmodel.h.
Referenced by data().
The documentation for this class was generated from the following files:
channelmodel.h
channelmodel.cpp