Small RSS: sFeedUpdater Class Reference
sFeedUpdater Class Reference
#include <sfeedupdater.h>
Public Slots
void startTimer (const int interval)
void stopTimer ()
void pollOne (QString url)
Signals
void newData ()
Public Member Functions
sFeedUpdater (QObject *parent=nullptr)
Private Slots
void finished (QNetworkReply *reply)
void timeout ()
Private Member Functions
void processXML (QByteArray data)
Private Attributes
QNetworkAccessManager * manager
int timerID
QNetworkCookieJar * jar
Detailed Description
Definition at line 23 of file sfeedupdater.h.
Constructor & Destructor Documentation
sFeedUpdater()
sFeedUpdater::sFeedUpdater (QObject * parent = nullptr) explicit
Definition at line 17 of file sfeedupdater.cpp.
References jar, manager, startTimer(), and timerID.
Member Function Documentation
finished
void sFeedUpdater::finished (QNetworkReply * reply) private slot
Definition at line 47 of file sfeedupdater.cpp.
References newData(), and processXML().
Referenced by startTimer().
newData
void sFeedUpdater::newData () signal
Referenced by finished().
pollOne
void sFeedUpdater::pollOne (QString url) slot
Definition at line 61 of file sfeedupdater.cpp.
References manager.
Referenced by timeout().
processXML()
void sFeedUpdater::processXML (QByteArray data) private
Definition at line 57 of file sfeedupdater.cpp.
Referenced by finished().
startTimer
void sFeedUpdater::startTimer (const int interval) slot
Definition at line 26 of file sfeedupdater.cpp.
References finished(), manager, and timerID.
Referenced by sFeedUpdater().
stopTimer
void sFeedUpdater::stopTimer () slot
Definition at line 32 of file sfeedupdater.cpp.
References timerID.
timeout
void sFeedUpdater::timeout () private slot
Definition at line 36 of file sfeedupdater.cpp.
References pollOne(), and timerID.
Member Data Documentation
jar
QNetworkCookieJar* sFeedUpdater::jar private
Definition at line 42 of file sfeedupdater.h.
Referenced by sFeedUpdater().
manager
QNetworkAccessManager* sFeedUpdater::manager private
Definition at line 40 of file sfeedupdater.h.
Referenced by pollOne(), sFeedUpdater(), and startTimer().
timerID
int sFeedUpdater::timerID private
Definition at line 41 of file sfeedupdater.h.
Referenced by sFeedUpdater(), startTimer(), stopTimer(), and timeout().
The documentation for this class was generated from the following files:
sfeedupdater.h
sfeedupdater.cpp