Small RSS: ChannelParser Class Reference
ChannelParser Class Reference
Class parsing the XML RSS info into ready to use structures.
#include <channelparser.h>
Classes
struct channelInfo
General info about the channel being added as parsed from XML (fields as per RFC)
struct encl
Enclosure structure as a possible part of item returned for the given RSS channel.
struct img
Substructure of ChannelParser::channelInfo with details of image (if supplied)
struct itemInfo
Representaion of a single item from a list returned for given RSS channel.
Signals
void channelParsed (bool result)
Signal emitted when parsing of the server reply is complete.
Public Member Functions
ChannelParser (QObject *parent=nullptr)
Generic constructor. Calls init() to set initial values.
bool parseData (QByteArray &data)
Method parsing data raw XML data returned from the server.
void clear ()
Clears internal data structures from any data.
void init ()
Inits internal data structures with default (empty or predefined) data.
channelInfo getChannelInfo () const
Getter method for parsed info about RSS channel.
QVector< itemInfo > getItemsInfo () const
Getter method returning list of entries in the RSS channel.
QString lastError () const
Human readable info about possible errors.
Private Attributes
channelInfo channel
Internal strucutre holding parsed channel info.
QVector< itemInfo > items
Internal strucutre holding published items for the channel.
QString errorStr
Internal member holding last error string.
Detailed Description
Class parsing the XML RSS info into ready to use structures.
Definition at line 13 of file channelparser.h.
Constructor & Destructor Documentation
ChannelParser()
ChannelParser::ChannelParser (QObject * parent = nullptr) explicit
Generic constructor. Calls init() to set initial values.
Parameters
parent Optional parent object or nullptr
Definition at line 3 of file channelparser.cpp.
References init().
Member Function Documentation
channelParsed
void ChannelParser::channelParsed (bool result) signal
Signal emitted when parsing of the server reply is complete.
Parameters
result True upon success, false if parsing failed
Referenced by parseData().
clear()
void ChannelParser::clear ()
Clears internal data structures from any data.
Definition at line 8 of file channelparser.cpp.
References init().
Referenced by parseData().
getChannelInfo()
ChannelParser::channelInfo ChannelParser::getChannelInfo () const
Getter method for parsed info about RSS channel.
Returns
Strucutre filled with data
See also
ChannelParser::channelInfo()
Definition at line 41 of file channelparser.cpp.
References channel.
Referenced by addChannel::finished().
getItemsInfo()
QVector< ChannelParser::itemInfo > ChannelParser::getItemsInfo () const
Getter method returning list of entries in the RSS channel.
Returns
QVector of entries or empty QVector() if no items are published
See also
ChannelParser::itemInfo()
Definition at line 45 of file channelparser.cpp.
References items.
Referenced by addChannel::finished().
init()
void ChannelParser::init ()
Inits internal data structures with default (empty or predefined) data.
Definition at line 12 of file channelparser.cpp.
References ChannelParser::channelInfo::category, channel, ChannelParser::channelInfo::copyright, ChannelParser::channelInfo::description, ChannelParser::channelInfo::docs, errorStr, ChannelParser::channelInfo::generator, ChannelParser::img::height, ChannelParser::channelInfo::image, items, ChannelParser::channelInfo::language, ChannelParser::channelInfo::lastBuildDate, ChannelParser::img::link, ChannelParser::channelInfo::link, ChannelParser::channelInfo::managingDirector, ChannelParser::channelInfo::pubDate, ChannelParser::channelInfo::skipDays, ChannelParser::channelInfo::skipHours, ChannelParser::img::title, ChannelParser::channelInfo::title, ChannelParser::channelInfo::ttl, ChannelParser::img::url, ChannelParser::channelInfo::webMaster, and ChannelParser::img::width.
Referenced by addChannel::addChannel(), ChannelParser(), and clear().
lastError()
QString ChannelParser::lastError () const
Human readable info about possible errors.
Returns
Unicode error string or empty QString()
Definition at line 100 of file channelparser.cpp.
References errorStr.
parseData()
bool ChannelParser::parseData (QByteArray & data)
Method parsing data raw XML data returned from the server.
Parameters
data Raw byte array with XML data
Returns
true on success, false on parsing error
See also
lastError()
Definition at line 49 of file channelparser.cpp.
References channel, channelParsed(), clear(), ChannelParser::channelInfo::copyright, ChannelParser::channelInfo::description, ChannelParser::itemInfo::description, ChannelParser::channelInfo::docs, errorStr, ChannelParser::channelInfo::generator, items, ChannelParser::channelInfo::language, ChannelParser::channelInfo::lastBuildDate, ChannelParser::channelInfo::link, ChannelParser::itemInfo::link, ChannelParser::channelInfo::managingDirector, ChannelParser::channelInfo::pubDate, ChannelParser::itemInfo::pubDate, ChannelParser::channelInfo::skipDays, ChannelParser::channelInfo::skipHours, ChannelParser::channelInfo::title, ChannelParser::itemInfo::title, ChannelParser::channelInfo::ttl, and ChannelParser::channelInfo::webMaster.
Referenced by addChannel::finished().
Member Data Documentation
channel
channelInfo ChannelParser::channel private
Internal strucutre holding parsed channel info.
See also
ChannelParser::channelInfo()
ChannelParser::getChannelInfo()
Definition at line 109 of file channelparser.h.
Referenced by getChannelInfo(), init(), and parseData().
errorStr
QString ChannelParser::errorStr private
Internal member holding last error string.
Definition at line 111 of file channelparser.h.
Referenced by init(), lastError(), and parseData().
items
QVector<itemInfo> ChannelParser::items private
Internal strucutre holding published items for the channel.
See also
ChannelParser::itemInfo
ChannelParser::getItemsInfo()
Definition at line 110 of file channelparser.h.
Referenced by getItemsInfo(), init(), and parseData().
The documentation for this class was generated from the following files:
channelparser.h
channelparser.cpp