Small RSS: TNCookieJar Class Reference
TNCookieJar Class Reference
#include <tncookiejar.h>
Public Member Functions
TNCookieJar (QObject *parent=nullptr, const QString path=QString())
bool insertCookie (const QNetworkCookie &cookie)
bool deleteCookie (const QNetworkCookie &cookie)
bool updateCookie (const QNetworkCookie &cookie)
void deleteCookies ()
Private Member Functions
bool saveCookie (const QNetworkCookie &cookie) const
QNetworkCookie loadCookie (const QString fname) const
QFileInfoList listCookies () const
Private Attributes
QString apath
Detailed Description
Definition at line 10 of file tncookiejar.h.
Constructor & Destructor Documentation
TNCookieJar()
TNCookieJar::TNCookieJar (QObject * parent = nullptr, const QString path = QString())
Definition at line 3 of file tncookiejar.cpp.
References apath, listCookies(), and loadCookie().
Member Function Documentation
deleteCookie()
bool TNCookieJar::deleteCookie (const QNetworkCookie & cookie)
Definition at line 77 of file tncookiejar.cpp.
deleteCookies()
void TNCookieJar::deleteCookies ()
Definition at line 82 of file tncookiejar.cpp.
References apath.
Referenced by CacheClass::clearCookies().
insertCookie()
bool TNCookieJar::insertCookie (const QNetworkCookie & cookie)
Definition at line 65 of file tncookiejar.cpp.
References saveCookie().
listCookies()
QFileInfoList TNCookieJar::listCookies () const private
Definition at line 92 of file tncookiejar.cpp.
References apath.
Referenced by TNCookieJar().
loadCookie()
QNetworkCookie TNCookieJar::loadCookie (const QString fname) const private
Definition at line 16 of file tncookiejar.cpp.
Referenced by TNCookieJar().
saveCookie()
bool TNCookieJar::saveCookie (const QNetworkCookie & cookie) const private
Definition at line 34 of file tncookiejar.cpp.
References apath.
Referenced by insertCookie(), and updateCookie().
updateCookie()
bool TNCookieJar::updateCookie (const QNetworkCookie & cookie)
Definition at line 71 of file tncookiejar.cpp.
References saveCookie().
Member Data Documentation
apath
QString TNCookieJar::apath private
Definition at line 21 of file tncookiejar.h.
Referenced by deleteCookies(), listCookies(), saveCookie(), and TNCookieJar().
The documentation for this class was generated from the following files:
tncookiejar.h
tncookiejar.cpp